Fix and update semantics for ops.enable() and ops.disable()
sched-ext/sched_ext pull request #100
Opened 2023-12-14 20:03 UTC by Decave

- A task's scx.weight is properly set before ops.enable() on the fork path, but not on the BPF prog load path. Set it properly for both.
- ops.enable() (and a corresponding ops.disable()) is called once for every task on the system on the BPF prog load path, or the fork path. It would be useful to instead call ops.enable() whenever a task is about to run on scx, and ops.disable() whenever a task is no longer running on scx.

2023-12-22 00:48 UTC, htejun commented on include/linux/sched/ext.h
> +			    struct scx_enable_args *args);
As discussed in the chat, it'd be great if we can just do four methods - init/exit_task() and enable/disable(). We'll probably want to add an argument to exit_task() to indicate whether it's being called to cancel init or it's for a task exit.

2023-12-22 00:48 UTC, htejun commented on kernel/sched/ext.c
> +static void scx_ops_disable_task(struct task_struct *p, bool transitioning)
I think it'd be cleaner if we separate out disabling and exiting into separate functions. If you look at the body of the function, they're pretty separate paths anyway.

2023-12-22 00:48 UTC, htejun commented on kernel/sched/ext.c
>  {
Maybe match the function name so that it's `scx_ops_init_task()`?

2023-12-22 00:48 UTC, htejun commented on kernel/sched/ext.c
> +		p->scx.flags |= SCX_TASK_OPS_LOADABLE;
I don't understand what `LOADABLE` is doing. What's its role?

2023-12-22 00:48 UTC, htejun commented on kernel/sched/ext.c
> +	    (SCX_TASK_OPS_INITIALIZED | SCX_TASK_OPS_LOADABLE)) {
Can we do `INITED` and `ENABLED`?

2023-12-22 00:54 UTC, htejun commented
So, one thing which is weird is `scx_enable_args.cgroup`. This is provided because the associated cgroup is not available at the time of `.prep_enable()` and it just carries over to `.enable()` because they're considered two continued parts of the same operation. After this change, `init_task` and `enable` are distinct steps and while `init_task` would need the explicit cgroup argument, `enable` won't. So, I guess what needs to happen is introducing `scx_init_task_args` and remove cgroup from` scx_enable_args`?

2024-01-02 20:29 UTC, Decave commented on kernel/sched/ext.c
> +		p->scx.flags |= SCX_TASK_OPS_LOADABLE;
`LOADABLE` reflects a task with the following properties:
1. It has been initialized with `ops.init_task()`
2. It can no longer be cancelled with `ops.cancel_init()`
3. It is _not_ actively enabled.

In other words, it's there to allow us to know when to issue `ops.cancel_init()` rather than `ops.exit_task()`. `ops.cancel_init()` is invoked when we want to notify the scheduler that a task that was previously initialized with `ops.init_task()` was never actually fully initialized. We could achieve the same thing by passing something like a `struct scx_exit_args *args` to `ops.exit_task()` and instead always invoking that.

2024-01-02 20:33 UTC, Decave commented on kernel/sched/ext.c
> +	    (SCX_TASK_OPS_INITIALIZED | SCX_TASK_OPS_LOADABLE)) {
See the comment above r.e. LOADABLE -- the problem is that we need that flag to know whether a task was ever _fully_ initialized. If we used `ENABLED`, I think we'd need something like `ENABLABLE` for that flag if we wanted to be consistent.

2024-01-02 20:35 UTC, Decave commented on kernel/sched/ext.c
> +static void scx_ops_disable_task(struct task_struct *p, bool transitioning)
Hmm, but we have to invoke `ops.disable()` on the exit path as well, no?

2024-01-02 21:02 UTC, htejun commented on kernel/sched/ext.c
> +static void scx_ops_disable_task(struct task_struct *p, bool transitioning)
Ah, right, the branch is between `.disable` and `.cancel_init` which should go away if we get rid of `.cancel_init`.

2024-01-02 21:07 UTC, Decave commented on kernel/sched/ext.c
> +static void scx_ops_disable_task(struct task_struct *p, bool transitioning)
Not sure I'm 100% following. I think we'd still have that branch even if we got rid of `.cancel_init()` because we would have to know which arg we should pass to `.exit_task()`, right?

2024-01-02 23:27 UTC, Decave commented
> So, one thing which is weird is `scx_enable_args.cgroup`. This is provided because the associated cgroup is not available at the time of `.prep_enable()` and it just carries over to `.enable()` because they're considered two continued parts of the same operation. After this change, `init_task` and `enable` are distinct steps and while `init_task` would need the explicit cgroup argument, `enable` won't. So, I guess what needs to happen is introducing `scx_init_task_args` and remove cgroup from` scx_enable_args`?

@htejun so I applied most of your suggestions and pushed. The ones I haven't applied are:
- Splitting disable and exit into separate paths, as we can't get rid of that branch for the `ops.cancel_init()` path (even though it's now `ops.exit_task()` as we have to know when a task failed to be fully initialized.
- Changing `SCX_TASK_OPS_LOADED` to `SCX_TASK_OPS_ENABLED`, as I think we'd also have to `SCX_OPS_TASK_LOADABLE` to `SCX_TASK_OPS_ENABLABLE` to be consistent. I'm OK with applying that if you want but it's obviously a pretty weird word so IMO it doesn't do the readability any favors.
- I updated `ops.enable()` to not take an arg, as now it doesn't actually receive anything. I'm happy to make empty struct args to `ops.enable()` and `ops.disable()` for future proofing, though we should probably be consistent and apply that to other callbacks too like `ops.init()` if we decide to go that route. IMO it would be better to keep the args minimal until we know we need them, assuming we can rely on some libbpf magic to help us with resolving the correct struct_ops map at load time.

I'm happy to revisit any of the above, just let me know.

2024-01-04 08:01 UTC, htejun requested changes
I'm afraid I don't like the code. It's verbose and confusing at the same time, which isn't a good combination and things like `if (loadable || loaded)` are actively confusing - ie. does that mean something loaded may not be loadable? Why is it loaded and loadable when none of the verbs are load? Why do we still need `.cancel_init`? Can we just not distinguish `loadable`? Or at least make it a flag which indicates `has ever been enabled` which doesn't actively participate in state transitions and just used in a specific spot to tell `.exit_task` what's going on?

I like the eventual behavior this PR is targeting but there gotta be a more intuitive way to implement this.

2024-01-04 14:41 UTC, Decave commented
No problem, let me take a stab at cleaning this up a bit

2024-01-05 04:24 UTC, Decave commented
@htejun this should be ready for another review. Thanks for pushing back on the last iteration -- I think this one is way cleaner and more readable.

2024-01-05 15:41 UTC, htejun approved these changes
I left a few comments but generally looks good to me. Thanks a lot for reworking it.

2024-01-05 15:41 UTC, htejun commented on include/linux/sched/ext.h
> +};
- Can we shorter names? e.g. NONE, INITING, INITED, ENABLED. If that's too ugly, how about NONE, INIT, READY, ENABLED?
- Can we put this into two bits in the flags field and have get/set_task_state helpers? The sanity checks on allowed state transitions can be moved into the set helper.

2024-01-05 15:41 UTC, htejun commented on kernel/sched/ext.c
> +			p->scx.task_state = SCX_TASK_INITIALIZED;
The comment block above says PREPPED -> ENABLED. Maybe update together?

2024-01-05 15:41 UTC, htejun commented on include/linux/sched/ext.h
> +	enum scx_exit_task_kind	kind;
Can this just be a bool? I have a hard time imagining what other exit kinds there can be.

2024-01-05 15:49 UTC, Decave commented on include/linux/sched/ext.h
> +	enum scx_exit_task_kind	kind;
So one example I was considering but decided not to mention is if the task is cancelled because it's TASK_DEAD (see the `if (READ_ONCE(p->__state) != TASK_DEAD)` check in `scx_ops_enable()`) rather than because another task failed to be initialized in `ops.init_task()`. In that case the kind would maybe be something like `SCX_TASK_EXIT_DYING`. I can't think of any others, so if we definitely don't want to distinguish there we can make it a `bool`.

2024-01-05 15:55 UTC, Decave commented on include/linux/sched/ext.h
> +};
>how about NONE, INIT, READY, ENABLED?

will do

>Can we put this into two bits in the flags field and have get/set_task_state helpers? The sanity checks on allowed state transitions can be moved into the set helper.

hah, cute. sure, will do.

2024-01-05 16:28 UTC, Decave commented on include/linux/sched/ext.h
> +	enum scx_exit_task_kind	kind;
I'll just make it a bool. We can always change it to an enum if we need later

2024-01-05 16:39 UTC, merged