Allow dispatching from ops.select_cpu()
sched-ext/sched_ext pull request #104
Opened 2024-01-02 18:29 UTC by Decave

A common pattern in schedulers is to find and reserve an idle core in
`ops.select_cpu()`, and to then use a task local storage map to specify
that the task should be enqueued in `SCX_DSQ_LOCAL` on the `ops.enqueue()`
path. At the same time, we also have a special `SCX_TASK_ENQ_LOCAL`
enqueue flag which is used by `scx_select_cpu_dfl()` to notify
`ops.enqueue()` that it may want to do a local enqueue.

Taking a step back, direct dispatch is something that should be
supported from the `ops.select_cpu()` path as well. At the end of the day,
it's on the same "enqueue path" as `ops.enqueue()`, and if we have the
contract be that doing a direct dispatch to `SCX_DSQ_LOCAL` will dispatch
the task to the local CPU of whatever is returned by `ops.select_cpu()`, it
should improve the ergonomics of `ops.select_cpu()` quite nicely. With that
in mind, let's just extend the API a bit to support direct dispatch from
`ops.select_cpu()`.

2024-01-03 10:03 UTC, htejun requested changes
Overall LGTM. Some minor comments within.

2024-01-03 10:03 UTC, htejun commented on include/linux/sched/ext.h
> +	SCX_OPS_ENQ_DFL_NO_DISPATCH= 1LLU << 3,
It's a word salad no matter what, so maybe it'd be better to name it more accurately? How about sth like `SCX_OPS_SELCPU_DFL_NO_DDSP` for "select_cpu_default no direct dispatch"?

2024-01-03 10:03 UTC, htejun commented on include/linux/sched/ext.h
> +	SCX_OPS_ENQ_DFL_NO_DISPATCH= 1LLU << 3,
I wonder whether we can skip the flag and require users to implement custom select_cpu if they want to override the behavior. e.g. we can provide `s32 scx_bpf_select_cpu_dfl(struct task_struct *p, s32 prev_cpu, u64 wake_flags, bool *end_direct` which is also used to implement `select_cpu_dfl`. Then, we can avoid adding the specialized flag while allowing users to achieve the behavior if desired.

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +		return -EINVAL;
Can we push this later so that we can fail with scx_ops_error() and report more details on why it's being failed?

2024-01-03 10:03 UTC, htejun commented on include/linux/sched/ext.h
> +	SCX_TASK_ENQ_DIRECT	= 1 << 2, /* task was directly dispatched */
Maybe "task is to be directly dispatched" is more intuitive?

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +		p->scx.dsq_flags |= SCX_TASK_DSQ_ON_PRIQ;
This probably is safe because while dsq_flags is synchronized the associated dsq's lock, the task here is not associated with a dsq and the field shouldn't be used. That said, I don't think it's a good idea to use this flag field like this. Let's just add another p->scx.flags field.

Another way to go about it is adding another `SCX_DSQ_FLAG_` bit. We have plenty of bits there and that would encode all the necessary information into `ddsq_id`.

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +	p->scx.flags |= SCX_TASK_ENQ_DIRECT;
Can't we use whether ddsq_id is INVALID? The code is initializing that value to INVALID but not depending on that anywhere.

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +	WARN_ON_ONCE(!(p->scx.flags & SCX_TASK_ENQ_DIRECT));
This is definitely subjective but I feel this is too much WARN_ON_ONCE()'s. Both conditions are established recently by tightly coupled code, one just before the function is being called.

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +static void direct_dispatch(struct task_struct *p, u64 dsq_id, u64 enq_flags)
Given that `mark_direct_dispatch()` directly modifies `p->ddsq_id`, it probably would make sense to make `direct_dispatch()` to consume and modify it directly too.

2024-01-03 10:03 UTC, htejun commented on kernel/sched/ext.c
> +		WARN_ON_ONCE(dsq->id != SCX_DSQ_GLOBAL);
Again, this WARN_ON_ONCE() seems excessive. Besides, isn't this an already existing path where BPF scheduler can trigger `WARN_ON_ONCE` in `dispatch_enqueue()`? ie. Isn't the correct thing to do convert `dispatch_enqueue()` trigger `scx_ops_error()` instead of `WARN_ON_ONCE()` when `PRIQ` is specified for a builtin dsq?

The current code is really weird because the global dsq fallback path is already an `scx_ops_error()` path. The BPF scheduler is getting killed no matter what. But for that path, we are adding a work around to drop the `PRIQ` flag along with `WARN_ON_ONCE()` to check that the fallback is indeed `global_dsq` so that the error path doesn't trigger `WARN_ON_ONCE()` in `direct_dispatch()`. It's too elaborate for abort handling.

2024-01-03 15:00 UTC, Decave commented on include/linux/sched/ext.h
> +	SCX_OPS_ENQ_DFL_NO_DISPATCH= 1LLU << 3,
Sounds good, let's do that. Or, what if we just did `s32 scx_bpf_select_cpu_dfl(struct task_struct *p, s32 prev_cpu, u64 wake_flags)`, and then left it up to the caller as to whether or not they wanted to dispatch?

2024-01-03 15:02 UTC, Decave commented on include/linux/sched/ext.h
> +	SCX_TASK_ENQ_DIRECT	= 1 << 2, /* task was directly dispatched */
Yeah that comment is weird. How about "task is recommended to be directly dispatched"? Given that it's really more of a recommendation than a directive.

2024-01-03 15:03 UTC, Decave commented on kernel/sched/ext.c
> +	p->scx.flags |= SCX_TASK_ENQ_DIRECT;
Yeah, good idea

2024-01-03 15:18 UTC, Decave commented on kernel/sched/ext.c
> +	WARN_ON_ONCE(!(p->scx.flags & SCX_TASK_ENQ_DIRECT));
I don't feel strongly so will remove, but I generally like to err on the side of being liberal with code like this which checks assertions that a function is relying on. Though in the past I've worked on a kernel where such error checks are compiled out on "release" kernels, so I should probably adjust for Linux.

2024-01-03 15:20 UTC, Decave commented on kernel/sched/ext.c
> +		WARN_ON_ONCE(dsq->id != SCX_DSQ_GLOBAL);
>Besides, isn't this an already existing path where BPF scheduler can trigger WARN_ON_ONCE in dispatch_enqueue()? ie. Isn't the correct thing to do convert dispatch_enqueue() trigger scx_ops_error() instead of WARN_ON_ONCE() when PRIQ is specified for a builtin dsq?

Yes, that's a great point. I'll make this change in a separate PR and will remove the excessive abort handling here.

2024-01-03 15:30 UTC, Decave commented on include/linux/sched/ext.h
> +	SCX_OPS_ENQ_DFL_NO_DISPATCH= 1LLU << 3,
The more I think about it, the more I like this idea. It would allow us to get rid of both flags. You don't need SCX_ENQ_LOCAL if you can know from the BPF prog whether the cpu returned by scx_bpf_select_cpu_dfl() != prev_cpu.

2024-01-03 16:13 UTC, Decave commented on kernel/sched/ext.c
> +		p->scx.dsq_flags |= SCX_TASK_DSQ_ON_PRIQ;
I'll go with replacing the `SCX_TASK_ENQ_DIRECT` flag with a `SCX_TASK_DDSP_PRIQ` flag. It feels kind of weird to add a dsq flag given that it takes away a bit from non-built-in DSQ IDs for what's a temporary state.

2024-01-03 16:15 UTC, Decave commented on include/linux/sched/ext.h
> +	SCX_TASK_ENQ_DIRECT	= 1 << 2, /* task was directly dispatched */
No longer applies now that we're using the ddsq_id.

2024-01-03 17:49 UTC, Decave commented
@htejun thanks for the thorough review -- please feel free to take another look when you have a moment.

2024-01-03 19:26 UTC, htejun commented on kernel/sched/ext.c
> +		p->scx.dsq_flags |= SCX_TASK_DSQ_ON_PRIQ;
We have 63 bits for builtin DSQ IDs when we have only 2 + nr_cpus builtin DSQs. So, we have room to spare there. But yeah either way is fine.

2024-01-04 02:01 UTC, htejun approved these changes
LGTM. Left a couple minor comments. Please feel free to merge. Longer term, I wonder whether it'd be possible to reduce the amount of boilerplating for test code.

2024-01-04 02:01 UTC, htejun commented on kernel/sched/ext.c
> +		goto err_disable;
Would this end up calling `.exit` without calling `.init`?

2024-01-04 02:01 UTC, htejun commented on tools/testing/selftests/scx/select_cpu_dfl.bpf.c
> +	if (enq_flags & SCX_ENQ_LOCAL)
This probably needs updating?

2024-01-04 03:12 UTC, Decave commented
> LGTM. Left a couple minor comments. Please feel free to merge. Longer term, I wonder whether it'd be possible to reduce the amount of boilerplating for test code.

Yep, that's on my todo list. Will probably move it up because I'm finding it pretty convenient to write these testcases and plan to do more.

2024-01-04 14:51 UTC, ByteLab-David commented on kernel/sched/ext.c
> +		goto err_disable;
Yeah it would. I figured that made sense as an API for the contract to be, "If you've invoked the scheduler incorrectly you'll get a chance to hear about it in `.exit`, but I think it would be weird to also invoke `.init` if we know the configuration is invalid. Let me know if you disagree

2024-01-04 19:42 UTC, htejun commented on kernel/sched/ext.c
> +		goto err_disable;
I think it's a bit too surprising. init/exit being paired is a pretty natural assumption to make and we don't really lose anything by validating ops after calling `.init`, right?

2024-01-04 20:50 UTC, Decave commented on kernel/sched/ext.c
> +		goto err_disable;
It's subjective and I don't feel strongly so can make this change, but I do think it's a bit weird to call `.init()` if the scheduler is immediately going to be invalidated. On the other hand, the scheduler can still fail to load after `.init()` if e.g. `.prep_enable()` fails, so it's probably fine. Will apply and then merge

2024-01-04 20:52 UTC, htejun commented on kernel/sched/ext.c
> +		goto err_disable;
So, we can avoid both by not calling `.exit` if `.init` hasn't been called but I'm not sure the added code would be worth it. In the end, the only thing that really matters is that the user gets a diagnostic message which is understandable.

2024-01-04 22:04 UTC, merged