Make the ponter passing to .dispatch MAYBE_NULL
sched-ext/sched_ext pull request #121
Opened 2024-01-17 02:14 UTC by ThinkerYzu

This patch marks the second argument of .dispatch with
PTR_MAYBE_NULL | PTR_TO_BTF_ID | PTR_TRUSTED in
bpf_scx_is_valid_access(). The verifier  will ensures the programs
always check if the argument is NULL before reading the pointed memory.

2024-01-17 19:17 UTC, htejun requested changes
Looks good to me. I left a comment asking for a trivial change.

2024-01-17 19:17 UTC, htejun commented on kernel/sched/ext.c
> +        }
This looks great but can you please separate this out into its own function and add a bit of comment explaining what's happening?

2024-01-17 20:55 UTC, Decave reviewed
Thanks a lot for taking care of this. LGTM modulo nits

2024-01-17 20:55 UTC, Decave commented on kernel/sched/ext.c
> +        if (strcmp(mname, "dispatch") == 0 && off == sizeof(__u64) && type == BPF_READ) {
Could you please add a comment here explaining what we're checking here and why this corresponds to the `prev` arg of the callback?

2024-01-17 20:55 UTC, Decave commented on kernel/sched/ext.c
>  	if (type != BPF_READ)
If you bring this check to the beginning of the function, you don't have to check `BPF_READ` above

2024-01-17 20:55 UTC, Decave commented on tools/testing/selftests/scx/Makefile
> +
This is fine -- in a follow-on change I'll update the recipe to check if there's a _fail variant of a prog and also take that as a conditional dependency

2024-01-18 17:26 UTC, ThinkerYzu commented on kernel/sched/ext.c
> +        }
Sure

2024-01-18 17:27 UTC, ThinkerYzu commented on kernel/sched/ext.c
>  	if (type != BPF_READ)
Agree

2024-01-18 23:57 UTC, Decave approved these changes

2024-01-19 23:34 UTC, htejun approved these changes

2024-01-19 23:35 UTC, merged