use resizing of datasec maps in examples
sched-ext/sched_ext pull request #20
Opened 2023-06-15 22:45 UTC by inwardvessel

there are some percpu arrays in the example schedulers that can make use of a recent libbpf feature that allows for resizing global data sections. for select arrays, they can be placed in custom named data sections and then resized to match the actual cpu count on a given host.

shown below is the BTF dump of the central and pair example scheduler programs that shows the array lengths have changed (nr_elements) to match the 12-cpu host they were tested on. note the linkage has also changed. this is a result of making the arrays non-static which was needed to access them through the skeleton for resizing in the userspace program.

central_dispatch before:
[742] ARRAY '(anon)' type_id=97 index_type_id=4 nr_elems=4096
[743] VAR 'cpu_gimme_task' type_id=742, linkage=static
[744] ARRAY '(anon)' type_id=53 index_type_id=4 nr_elems=4096
[745] VAR 'cpu_started_at' type_id=744, linkage=static

central_dispatch after:
[743] VAR 'cpu_gimme_task' type_id=867, linkage=global
[745] VAR 'cpu_started_at' type_id=868, linkage=global
[867] ARRAY '(anon)' type_id=97 index_type_id=4 nr_elems=12
[868] ARRAY '(anon)' type_id=53 index_type_id=4 nr_elems=12

pair_dispatch before:
[675] ARRAY '(anon)' type_id=673 index_type_id=4 nr_elems=4096
[676] VAR 'pair_cpu' type_id=675, linkage=global
[733] ARRAY '(anon)' type_id=669 index_type_id=4 nr_elems=4096
[734] VAR 'pair_id' type_id=733, linkage=global
[735] VAR 'in_pair_idx' type_id=733, linkage=global

pair_dispatch after:
[730] VAR 'pair_cpu' type_id=890, linkage=global
[732] VAR 'pair_id' type_id=891, linkage=global
[733] VAR 'in_pair_idx' type_id=892, linkage=global
[890] ARRAY '(anon)' type_id=727 index_type_id=4 nr_elems=12
[891] ARRAY '(anon)' type_id=667 index_type_id=4 nr_elems=12
[892] ARRAY '(anon)' type_id=667 index_type_id=4 nr_elems=12

the existing MEMBER_VPTR() macro was no longer applicable to use on these select arrays, because it uses the compile-time length so it caused verification failures when attempting to access an array element at an index greater than the initial size. a variation on this macro was added that accepts a size argument in order to match the newly resized arrays.

2023-06-22 05:17 UTC, anakryiko commented on tools/sched_ext/scx_common.bpf.h
> +#define MEMBER_VPTR_SZ(base, member, sz) (typeof(base member) *)({		\
this macro will only ever be used with arrays, most probably, so I wonder if it would be better to just have an array-specific macro ARRAY_ELEM_PTR(base, idx, cnt), where cnt is actual size of the array (so you can derive byte size as `sizeof(base[0]) * cnt`

2023-06-22 05:17 UTC, anakryiko commented on tools/sched_ext/scx_example_central.bpf.c
> +			gimme = MEMBER_VPTR_SZ(cpu_gimme_task, [cpu],
and this could become just

```
gimme = ARRAY_ELEM_PTR(cpu_gimme_task, cpu, nr_cpu_ids);
```

2023-06-22 05:17 UTC, anakryiko commented on tools/sched_ext/scx_example_central.c
> +	assert(!bpf_map__set_value_size(skel->maps.data_cpu_gimme_task,
nit: assert() is probably an overkill here, I'd drop it in favor of more succinct code

2023-06-22 05:17 UTC, anakryiko commented on tools/sched_ext/scx_example_pair.c
> +	bpf_map__set_max_entries(skel->maps.pair_ctx, skel->rodata->nr_cpu_ids);
original size was MAX_CPU/2, so should this be nr_cpu_ids/2 ?

2023-06-22 05:17 UTC, anakryiko commented on tools/sched_ext/scx_example_pair.c
> +			skel->rodata_pair_cpu->pair_cpu[i + stride] = i;
wouldn't `i+stride` overflow beyond array size? should it be `(i + stride) % nr_cpu_ids`?

2023-06-27 22:43 UTC, inwardvessel commented on tools/sched_ext/scx_common.bpf.h
> +#define MEMBER_VPTR_SZ(base, member, sz) (typeof(base member) *)({		\
it's a good idea. changed to an array specific macro.

2023-06-27 22:44 UTC, inwardvessel commented on tools/sched_ext/scx_example_central.c
> +	assert(!bpf_map__set_value_size(skel->maps.data_cpu_gimme_task,
fair enough. removed.

2023-06-27 23:10 UTC, inwardvessel commented on tools/sched_ext/scx_example_pair.c
> +	bpf_map__set_max_entries(skel->maps.pair_ctx, skel->rodata->nr_cpu_ids);
ok, I updated to be consistent. it originally seemed arbitrary since it was MAX_CPUS/2 (4096/2), so I didn't think it was necessary to divide to save space now that it was potentially much smaller (matching the actual cpu count). I also did consider a cpu count of 1 at the time but now I realize that this program needs at least 2 cpu's to function correctly. could be wrong, but I made an issue about this https://github.com/sched-ext/sched_ext/issues/28

2023-06-27 23:19 UTC, inwardvessel commented on tools/sched_ext/scx_example_pair.c
> +			skel->rodata_pair_cpu->pair_cpu[i + stride] = i;
I think this question is related more to the original code so I opened an issue for this #29 . not the definitive answer, but it seems that it does not overflow in the case where stride is `nr_cpu_ids / 2`, since the second half array elements become positive values before they are visited so the conditional is not entered for them. it seems in this case you could just iterate half the array and be done, but see the issue I linked because that might not be feasible for other stride values.

2023-06-28 17:26 UTC, inwardvessel commented on tools/sched_ext/scx_example_pair.c
> +			skel->rodata_pair_cpu->pair_cpu[i + stride] = i;
resolved in `sched_ext` branch.

2023-06-28 17:26 UTC, inwardvessel commented
rebased on latest `sched_ext`

2023-06-30 19:06 UTC, anakryiko approved these changes
LGTM

2023-07-19 16:44 UTC, inwardvessel commented
rebased with no code changes

2023-07-20 00:59 UTC, Decave reviewed
So, I think it probably makes sense to land this for the sake of optimization and not having to hard-code MAX_CPUS. It does add some kind of odd-looking boilerplate, but I guess we'll have to live with it for now.

@htejun please chime in if you disagree or have other thoughts

Also, sorry @inwardvessel, but I think you may have to rebase one more time :-/

2023-07-20 00:59 UTC, Decave commented on tools/sched_ext/scx_central.c
> +	 * so they need to be assigned the new value.
Could you please make comments of the form:
```
/* 
 * Comment comment comment.
 * /
```

In other words, please match the existing style of the other schedulers, and please use correct grammar / punctuation, etc.

2023-07-20 00:59 UTC, Decave commented on tools/sched_ext/scx_common.bpf.h
> +#define ARRAY_ELEM_PTR(arr, i, n) (typeof(arr[i]) *)({		\
Could you please align the `\`'s?

2023-07-20 00:59 UTC, Decave commented on tools/sched_ext/scx_pair.c
> +	/* resize arrays so their element count is equal to cpu count.
Same here r.e. comment

2023-07-21 19:06 UTC, Decave requested changes

2023-07-21 19:06 UTC, Decave commented on tools/sched_ext/scx_central.bpf.c
> +u64 cpu_started_at[1] SEC(".data.cpu_started_at");
Can we add a macro to hide the complexity here? Something like this:

```
#define RESIZABLE_ARRAY(__var) __var[1] SEC(".data.##__var")
```

2023-07-21 19:06 UTC, Decave commented on tools/sched_ext/scx_central.c
> +	skel->data_cpu_started_at = bpf_map__initial_value(skel->maps.data_cpu_started_at, &sz);
Could you also please add a helper (with documentation) that encapsulates all of this reassignment boilerplate as well?

2023-08-02 19:31 UTC, inwardvessel commented
@Decave I made updates to address all comments. agreed on the boilerplate. at this point, the nature of resizing bpf arrays is really a side effect of resizing the actual data sections that contain them. so there's no direct way to say "resize this array". what we are really saying is "resize this map which happens to be the data section that contains the array I want resized". I added some macros based on your feedback. maybe they can be candidates for libbif itself so as to ease usage in cases like this.

2023-08-07 23:32 UTC, Decave reviewed
This is looking much better! Overall it's pretty close to landing, just had a few more nits / questions. Thanks for working on this.

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_user_common.h
> +	} while (0)
nit: Could you please align the `\`'s?

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_pair.c
> -			   stride, i, j, skel->rodata->pair_cpu[j]);
Did you mean to remove this check?

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_user_common.h
> + * RESIZE_ARRAY - Convenience macro for resizing a bpf array
s/bpf/BPF

here and elsewhere in the comment

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_user_common.h
> + * @datasec: the data section of the bpf program in which to the array exists
s/data/ELF?

In general I wonder if this arg would be better named `elfsec`. What do you think?

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_user_common.h
> +				sizeof(skel->datasec##_##arr->arr[0]) * n); \
Could you please surround `n` in parentheses?

2023-08-07 23:32 UTC, Decave commented on tools/sched_ext/scx_common.bpf.h
> +		  [max]"r"(sizeof(arr[0]) * (n - 1)));				\
Could you please surround `n` in its own parens?

2023-08-14 21:30 UTC, inwardvessel commented on tools/sched_ext/scx_pair.c
> -			   stride, i, j, skel->rodata->pair_cpu[j]);
good catch. reverted.

2023-08-14 21:30 UTC, inwardvessel commented on tools/sched_ext/scx_user_common.h
> + * @datasec: the data section of the bpf program in which to the array exists
sounds good, made the change.

2023-08-14 21:33 UTC, Decave approved these changes

2023-08-14 21:39 UTC, merged