scx: Print scheduler state in panic message
sched-ext/sched_ext pull request #66
Opened 2023-11-01 17:16 UTC by Decave

It would be useful to see what the sched_ext scheduler state is, and what scheduler is running, at panic time. Let's add a hook and print that information.

2023-11-03 16:44 UTC, Decave commented
@htejun updated this to only print when the scheduler is enabled, and allowed the behavior to be toggled with a default-off Kconfig option.

2023-11-03 19:16 UTC, htejun commented
This probably shouldn't be sth configurable as that can lead to a lot of confusion. Also, I'm not sure this is panic is the right hook up point. e.g. showing which scheduler is running can be very useful when hung task warning is triggered. So, it'd be better to be a part of basic cpu state dump which gets included whenever we printout backtrace.

2023-11-03 19:20 UTC, htejun commented
For an example, take a look at how print_worker_info() is used.

2023-11-07 00:31 UTC, htejun requested changes

2023-11-07 00:31 UTC, htejun commented on include/linux/sched/ext.h
> +static inline void print_scx_info(const char *log_lvl, struct task_struct *p);
empty body missing?

2023-11-07 00:31 UTC, htejun commented on kernel/sched/ext.c
> + * task_struct itself is accessible.  While safe, this function isn't
Single space instead of double for consistency?

2023-11-07 00:31 UTC, htejun commented on kernel/sched/ext.c
> +	if (task_scx_enabled) {
This really should be gated on "is scx enabled on the system at all?" rather than "is this task on scx?"

2023-11-07 00:31 UTC, htejun commented on kernel/sched/ext.c
> +		task_rq = cpu_rq(task_cpu);
Prolly wanna test task_cpu is actually valid before cpu_rq().

2023-11-07 00:31 UTC, htejun commented on kernel/sched/ext.c
> +			delta = rq_clock - runnable_at;
Negative delta is great too.

2023-11-07 00:31 UTC, htejun commented on kernel/sched/ext.c
> +	       "task: scx enabled: %d, runnable time: %llu, ops_state: %lx" ,
How about sth like the following?
`sched_ext: $NAME ($STATE[+all])` if task is not on scx.
`sched_ext: $NAME ($STATE[+all]), task: runnable_at=[+-]DELTA state=$OPS_STATE` if on scx

2023-11-07 02:06 UTC, Decave commented on kernel/sched/ext.c
> +	if (task_scx_enabled) {
I think the `if (!scx_enabled()` above should address that?

2023-11-07 02:19 UTC, Decave commented on kernel/sched/ext.c
> +		task_rq = cpu_rq(task_cpu);
Not sure if `ops_cpu_valid()` is kosher to use here? Seems like exactly what we want though

2023-11-07 02:20 UTC, ByteLab-David commented on include/linux/sched/ext.h
> +static inline void print_scx_info(const char *log_lvl, struct task_struct *p);
This made me realize !EXT builds are broken in general. I'll send a separate PR to fix

2023-11-07 02:20 UTC, Decave commented on kernel/sched/ext.c
> +	       "task: scx enabled: %d, runnable time: %llu, ops_state: %lx" ,
Not 100% sure if this is what you wanted. Feel free to clarify

2023-11-07 02:33 UTC, htejun requested changes

2023-11-07 02:33 UTC, htejun commented on kernel/sched/ext.c
> +	enum scx_ops_enable_state state = scx_ops_enable_state();
Let's move decls into the blocks that they're used.

2023-11-07 02:33 UTC, htejun commented on kernel/sched/ext.c
> +		       READ_ONCE(scx_switching_all), delta, ops_state);
For all, I meant `"...(%s%s)...", all ? "+all" : ""`. Also, we prolly want `%+lld` for runnable timestamp to signify that it's a delta value and `0x%lx` for state.

2023-11-07 02:33 UTC, htejun commented on kernel/sched/ext.c
> +	pr_cont("\n");
Let's avoid pr_cont. When multiple cpus are printing, the msg fragments get all mixed up.

2023-11-07 03:01 UTC, htejun approved these changes

2023-11-07 03:01 UTC, merged